name: Build and Test

on:
    push:
      branches:
        - main
    pull_request:
        branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Run image
        uses: abatilo/actions-poetry@v2
      - name: View poetry --help
        run: poetry run pytest --cov=harlow_bindicator --cov-report xml --cov-report term
      - name: Coveralls
        uses: coverallsapp/github-action@v2
