name: Check Binday

on:
  workflow_dispatch:
  schedule:
    - cron: '43 3 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
      - name: checkout repository
        uses: actions/checkout@v4 
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install harlow-bindicator
      - name: Run Bindicator
        run: |
          harlow-bindicator --uprn ${{ secrets.UPRN }} --topic ${{ secrets.TOPIC }}
